/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.controllers.ui.MainKud;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class Main extends Application {

    private Parent mainUI;
    private Stage stage;
    private Scene sceneMain;

    private MainKud mainKud;

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        this.pantailakKargatu();
        stage.setTitle("Liburuak Partzial 2020");
        stage.setScene(sceneMain);
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderLiburuak = new FXMLLoader(getClass().getResource("/Main.fxml"));
        mainUI = (Parent) loaderLiburuak.load();
        mainKud = loaderLiburuak.getController();
        mainKud.setMain(this);
        sceneMain = new Scene(mainUI);
    }

}
